services:
  - type: web
    name: dalek-social
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app

    # a specialized code only for render hosting.It tells render specific things to do 
    # that will help run the code properly. we really don't nee it if you want to setup render manually or host the app
    # on other places (like your computer).
